build:
  image: python:3
  before_script:
    - pip install setuptools pypandoc
    - apt-get update -qy
    - apt-get install -y pandoc
    - pandoc --from=markdown --to=rst --output=README.rst README.md
  script:
    - python setup.py sdist bdist

test:
  image: python:3
  before_script:
    - pip install -r requirements.txt  
    - pip install pytest pytest-cov
  script:
    - pytest --cov-report term-missing --cov=./src/ ./tests/
  coverage: '/TOTAL\s+\d+\s+\d+\s+(\d+\%)/'
