name: test

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
  workflow_dispatch:

jobs:
  unittest:
    # needs: mirror
    runs-on: ubuntu-latest
    if: ${{ !startsWith(github.head_ref, 'docs-') && !startsWith(github.head_ref, 'release-') }}
    concurrency: # keep latest workflow and cancel exist workflow in PR
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    timeout-minutes: 40
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9"]
#        python-version: ["3.9, 3.10, 3.11"]
    steps:
    - uses: actions/checkout@v4
    - name: Install uv
      uses: astral-sh/setup-uv@v5
      with:
        version: "latest"
        enable-cache: true
        cache-dependency-glob: "uv.lock"

    - name: Setup Python virtual environment
      run: |
        uv python install ${{ matrix.python-version }} &&
        uv venv --python ${{ matrix.python-version }} &&
        uv sync --active --all-extras --all-groups &&
        source .venv/bin/activate

    - name: Run tests
      run: pytest

#      - name: Upload coverage reports to Codecov
#        uses: codecov/codecov-action@v5
#        with:
#          token: ${{ secrets.CODECOV_TOKEN }}
#          flags: unittests
